### PR TITLE
minor fixes

### LINKED ISSUE #3144: Update Cost Estimator
### Description

- remove Email-Wall 🙏 
- introduce logic for individuals

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #3144 

- update cost estimator
- remove email-wall
- update messages on cards
- updates `for/enterprise`

<a href="https://gitpod.io/#https://github.com/gitpod-io/website/pull/3150"></a>

### CODE REVIEW

**Comment by MichaelAring** [comment]
Looks great!

When checking, I just found two mistakes (see screenshots). At 11 hours of workspace consumption, it should jump to the $9 plan. At 23 hours, it should be more than $9 hours.

Screenshot 2022-12-13 at 17 17 02

Screenshot 2022-12-13 at 17 17 02

File: src/lib/contents/enterprise.ts [hunk 1]
```diff
@@ -18,17 +18,58 @@ export const exploreContents: ExploreSection = {
...
+}[] = [
   {
-    title: "SaaS",
-    text: "Gitpod, managed in the cloud for you. Secure data storage in the cloud and minimal setup cost. Scale users as you need with full flexibility.",
-    icon: {
-      src: "/svg/icons/cloud.svg",
-      alt: "Cloud Icon",
+    card: {
+      title: "Multi-tenant",
+      text: "Use Gitpod in our cloud with minimal setup time and effort and scale users as you need with full flexibility. Get started today with a no cost commitment",
```
Comment (MichaelAring) [inline src/lib/contents/enterprise.ts:28]:
```suggestion
      text: "Use Gitpod in our cloud with minimal setup time and effort and scale users as you need with full flexibility. Get started today with no cost commitment.",
```

**Review by MichaelAring — CHANGES_REQUESTED** [review]

**Review by MichaelAring — COMMENTED** [review]
removed link to security
