### PR TITLE
Fixed some edge cases.

### LINKED ISSUE #168: Small fixes on the career page
- [ ] the width of the pullet points in the job description variate

- [ ] the bullet points should be aligned with the first word (it's currently wrong if the sentence goes over two lines)

- [ ] the recent arrow symbol (v) should be replaced with the icon-arrow and scaled down

- [ ] the team-icon has a different width. The heads are thicker than the body

### PR DESCRIPTION
**Pull request by nisarhassan12**
Fixes #168 
image

### CODE REVIEW

File: src/components/ExpandableJob.tsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import * as React from 'react'
-
+import DownArrow from '../resources/down-arrow.svg';
```
Comment (jankeromnes) [inline src/components/ExpandableJob.tsx]: Do we really want to have two different "Down Arrow" icons? https://github.com/gitpod-io/website/blob/master/src/resources/Arrow_down.svg

File: src/components/ExpandableJob.tsx [hunk 2]
```diff
@@ -1,5 +1,6 @@
...
+import UpArrow from '../resources/up-arrow.svg';
```
Comment (jankeromnes) [inline src/components/ExpandableJob.tsx]: Couldn't we just `transform: scaleY(-1)` (or `transform: rotater(180deg)`) the "Down Arrow" icon in order to achieve an "Up Arrow"?

**Comment by jankeromnes** [comment]
(I took the liberty to rebase the commit for you. 😄 The conflict was pretty small.)

**Comment by jankeromnes** [comment]
Shipped! 🚀
