### PR TITLE
fix: docs-announcement banner

### LINKED ISSUE #1919: [docs]: languages and fameworks layout broken at the top.
image

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #1919

<a href="https://gitpod-staging.com/#https://github.com/gitpod-io/website/pull/1920"></a>

### CODE REVIEW

File: src/lib/components/docs/docs-content-layout.svelte [hunk 1]
```diff
@@ -29,9 +29,9 @@
     title: title ? title : "Gitpod Documentation",
   }}
 />
-<AnnouncementBanner />
 <div class="flex">
   <div class="content-docs prose md:px-4 max-w-none flex-auto min-w-0 xl:w-2/3">
+    <AnnouncementBanner />
```
Comment (Cahllagerfeld) [inline src/lib/components/docs/docs-content-layout.svelte:34]: Issue was that the Banner was outside of the prose-class

**Review by nisarhassan12 — APPROVED** [review]
Thanks @Cahllagerfeld for the Pr it LGTM.
